"""multi-column unique value contraint added to likes table

Revision ID: 570e1528bcda
Revises: a9cae5a9d450
Create Date: 2018-03-22 16:04:49.408710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570e1528bcda'
down_revision = 'a9cae5a9d450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('one_time_like', 'likes', ['user_id', 'message_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('one_time_like', 'likes', type_='unique')
    # ### end Alembic commands ###
